defmodule FormValidator.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :update_at, to: :updated_at

    rename table(:addresses), :update_at, to: :updated_at
  end

  def down do
    rename table(:addresses), :updated_at, to: :update_at

    rename table(:users), :updated_at, to: :update_at
  end
end