defmodule FormValidator.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :email, :text, null: false
      add :username, :text, null: false
      add :password, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :update_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:users, [:email], name: "users_email_index")

    create table(:addresses, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "addresses_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :number, :bigint
      add :street, :bigint
      add :city, :text
      add :state, :text
      add :postal_code, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :update_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop constraint(:addresses, "addresses_user_id_fkey")

    drop table(:addresses)

    drop_if_exists unique_index(:users, [:email], name: "users_email_index")

    drop table(:users)
  end
end
